### ISSUE TITLE
Main Menu -- No Option for Fan Control

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#19]
There is no option to manually regulate the nozzle fan through the LCD screen.

**Comment by slipstreamliner** [comment]
While this is certainly possible, we are somewhat lacking in LCD main menu screen space.  I'll attempt to place this on the screen without interfering with other menu items.  More info to come here.

**Comment by slipstreamliner** [comment]
This value seems to behave differently than others I've added to the menu screen.  I am able to control the case fan, which is set for thermostatic control.  This doesn't make any sense in itself, and may be the indication of a bug.  I am going to come back to this later today and address more some more critical issues for now.  It may be necessary to implement a workaround for this that's different than our other main menu control methods.

**Comment by slipstreamliner** [comment]
Woops -- did not mean to close this.

**Comment by ericl-m3d** [comment]
![img_0028 1](https://user-images.githubusercontent.com/38476827/49309177-56a2e800-f4a8-11e8-995a-dc0b2e4398f0.JPG)
![img_0027 1](https://user-images.githubusercontent.com/38476827/49309190-5f93b980-f4a8-11e8-89d6-c20db2890d0c.JPG)

**Comment by slipstreamliner** [comment]
Patch upcoming -- I have found a method that works.

**Comment by slipstreamliner** [comment]
Based on the file I uploaded last week, https://github.com/PrintM3D/Crane/blob/dev/SD%20Card%20Structure/MEMORYREFERENCES.MD in the root of the SD card folders for each model, I am going to make an update that needs to be tested for this particular issue.  The references we are provided with based on the LCD for the fan are as follows:

-300-398	Fan (N-300) percent full PWM e.g. 302 = fan 2 percent
-399	Current tool fan percent full PWM

This indicates that 300 should reference F0's value, 301 F1's value, and 302 F2's value.  I have put together a fix for this that should work, but seems to be problematic on my test machine.  I believe my crane bowden may have the Part Cooler and Case Fan connections reversed from the config we typically use.

File update coming soon with suggested test configuration.

**Comment by slipstreamliner** [comment]
Updated as requested.  Please check functionality -- I had an issue with the machine I was using for testing, need to take it apart for reconfiguration later but just operating on our agreed upon ports for now.  It worked okay for me when I adapted it to my configuration.
