### ISSUE TITLE
Bowden -- Crane Menu Artifact on 'Nozzle'

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#32]
There is a visual error in the LCD: The word "Nozzle" blocks part of the number "0".

The other visual errors you see in the pic is not actually there (camera nuisances).

![img_0026 1](https://user-images.githubusercontent.com/38476827/49242956-1f660580-f3da-11e8-8ae8-51441d97e2a4.JPG)

**Comment by slipstreamliner** [comment]
This one is strange.  Is this happening on all LCD modules?  I will test this locally.  That looks like a portion of one of the corruption artifacts we see upon power on.

**Comment by slipstreamliner** [comment]
I am not able to reproduce this currently -- please verify firmware version.

**Comment by ericl-m3d** [comment]
Firmware is 2.02RC2. 

Just a thought: could an issue with the LCD type, as seen with the knob direction?

**Comment by slipstreamliner** [comment]
@ericl-m3d I think so.  I haven't been able to duplicate this on either of my LCDs at this point.

**Comment by slipstreamliner** [comment]
@ericl-m3d Any opposition to closing this?  I don't have any other LCDs to verify on -- both of mine are not presenting this issue.  If you'd like to test again before closing, just leave a comment with the result.  I'm leaving this open for now.

**Comment by ericl-m3d** [comment]
Closing this.
