### ISSUE TITLE
Quad Temp Control Menu -- Hotend Value Returning Zero

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#38]
During a print session, the hotend value appears as zero (which is not correct).

![img_0027 1](https://user-images.githubusercontent.com/38476827/49304489-78956e00-f49a-11e8-8532-f18dd316ff08.JPG)

Both the standby and active temps are not zero.

**Comment by slipstreamliner** [comment]
Noted -- this is due to the memory reference specifically defined for the PT1000.  This is a remnant of that functionality.  I will produce the fix but at this point will need you to test it... give me a few moments.

**Comment by ericl-m3d** [comment]
The update did not fix the bug. @shoreliner

**Comment by slipstreamliner** [comment]
Thanks; working on this in tandem with #39 -- what seems odd here is that we are using the same value to populate the menu screen.  This will be closed along with the ticket that has been referenced.

**Comment by slipstreamliner** [comment]
Okay, new take on this:  Temperature Tuning/Prepare menus are now being redesigned.  This will ensure all models have a similar user experience, and allow me to simply start over on some of these files.  I anticipate fixing this today with a patch, but I need to rewrite a few items and test first.

**Comment by slipstreamliner** [comment]
To elaborate on this:

I suggest the creation of two menu items.  One in s_prepare(for Idle), and one for s_tune(while printing/paused).

s_prepare will have "Temperature Controls" added as a submenu with the items:
-Bed Temperature (Current val) / (Set value)
-Hotend Temperature(Current val) / (Set value)
-PID Autotune (Degree to Tune)

s_tune will have "Temperature Tuning" added as a submenu with the items:
-Bed Temperature (Current val) / (Set value)
-Hotend Temperature(Current val) / (Set value)

**Comment by slipstreamliner** [comment]
From now on -- this issue resolves #39 going forward.  If necessary, the request will be reopened.. as of now, the patch recreates both of these elements.

**Comment by slipstreamliner** [comment]
s_prepare is now updated along with a new s_temp_prepare sub-menu on all models. Please test in the "patchmenu" branch.

**Comment by slipstreamliner** [comment]
I have collapsed all of these issues into the menupatch branch.  This exists as a PR already with tailing commits.  @ericl-m3d could you test to confirm functionality on your side?  As noted above:

s_prepare will have "Temperature Controls" added as a submenu with the items:
-Bed Temperature (Current val) / (Set value)
-Hotend Temperature(Current val) / (Set value)
-PID Autotune (Degree to Tune)

s_tune will have "Temperature Tuning" added as a submenu with the items:
-Bed Temperature (Current val) / (Set value)
-Hotend Temperature(Current val) / (Set value)

**Comment by slipstreamliner** [comment]
Almost there -- had some issues with reading temp, and have resolved with config updates.  Currently testing updates prior to updating the branch.

**Comment by slipstreamliner** [comment]
This will be resolved as part of the RC5 Patch.

**Comment by slipstreamliner** [comment]
Fixed in PR #60
