### ISSUE TITLE
Quad Submenu -- Temp Control Returning Zero

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#39]
I go to use the x_temphadj menu file.

I notice the hotend value is not reflective of the current extruder's temp (this is during a print session).

![img_0028 1](https://user-images.githubusercontent.com/38476827/49305195-995ec300-f49c-11e8-947d-dffad736aee8.JPG)

**Comment by slipstreamliner** [comment]
This is just like #38... cleanup for thermistor change.  Fix incoming soon.

**Comment by slipstreamliner** [comment]
Resolved as per my notes in #38 -- this will be fixed with temp menu patch.
