### ISSUE TITLE
2.02RC4 Compatibility Issue

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#4]
Cannot access the s_prepare.

![img_0025 1](https://user-images.githubusercontent.com/38476827/49189716-6fdb5580-f33d-11e8-8972-4427c3259d8e.JPG)

**Comment by slipstreamliner** [comment]
Please explain when this issue occurs:

-On Startup?
-When Accessing a particular menu option?

**Comment by ericl-m3d** [comment]
Clicked the prepare button at the start up. Then this came up

**Comment by ericl-m3d** [comment]
This is occurring with the 2.02RC4 firmware version.

**Comment by slipstreamliner** [comment]
Should only be using firmware version 2.02RC2 -- I have tested locally and menu is still functional.  While the latest firmware is 2.02RC5, we have not decided to move to it yet.

**Comment by slipstreamliner** [comment]
Per our conversation we will begin testing for 2.02RC4; in the meantime this issue is resolved for the current version. Thanks!

**Comment by slipstreamliner** [comment]
Closed as per internal conversation -- this issue will be revisited soon.
