### ISSUE TITLE
Included Gcode for Prints

### ISSUE THREAD

**Issue by slipstreamliner** [PrintM3D/Crane#42]
Can we discuss the models that have already been sliced, noted here:

http://crane.printm3d.com/community-submissions-attributions/attributions

For inclusion on the official SD cards?  I believe that we should consider making each version similar where the Quad prints with 4-color mixing, the Dual prints with 2-color mixing, and the Bowden prints solid.

Any ideas here are welcome.  It's also not time-consuming whatsoever to produce additional slices.

**Comment by ericl-m3d** [comment]
I don't mind including any of these.

NOTE: There's currently a sliced model in both the bowden and quad. It's a crane micro spool holder (used for QC).

**Comment by slipstreamliner** [comment]
Spool Holder will be included.  Fulfilled here by commit.
