### ISSUE TITLE
Unloading Macros Request

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#44]
Need an unloading macros.

(There is an unloading section, probably house it in there.)

Suggested Commands:
```
M190 S150; Needs the wait, before retraction
G1 E-100:-100:-100:-100 F600; At least 100 mm retraction, recommended speed 5 mm/s
```

**Comment by slipstreamliner** [comment]
Sounds great to me, I'll add via commit across the board... Drives will vary per model. We could put this on the unload menu as a different sort of "retract all/unload all" than we one we have there now. Will close via commit after testing.

**Comment by slipstreamliner** [comment]
As noted in above commit -- remove_filament macros were added to each crane model.  Issue will be closed following addition of this to the LCD menu and any discussion necessary.

**Comment by slipstreamliner** [comment]
@ericl-m3d do you want to test these out before I add them to the menu?

**Comment by ericl-m3d** [comment]
Okay. Test them. I'll have to test them as well.

**Comment by ericl-m3d** [comment]
Edits to the macros. 

```
M190 S150; Needs the wait, before retraction
M120
M83
G1 E-100:-100:-100:-100 F600; At least 100 mm retraction, recommended speed 5 mm/s
M121
```
The M120 and M121 may not be necessary. I'm following the convention of the extrusion buttons in DWC.

Definitely the M83 needs to be there.

Use the is macros. Please add to menu.

**Comment by slipstreamliner** [comment]
Acknowledged. Will to and add to menu.

**Comment by slipstreamliner** [comment]
Marked as RC5 milestone.  Will be resolved on merge.

**Comment by slipstreamliner** [comment]
View the prior commit to see the updates made to x_funload -- do we need to make further changes?

**Comment by ericl-m3d** [comment]
There is no unloading macros present. Please add.

**Comment by Tylerun** [comment]
I am unable to attach photo but in quad web intetface macro is present and active.

**Comment by slipstreamliner** [comment]
Both loading and unloading macros are being overhauled for the 2.02 official release. Adding to milestone and will resolve upon branch merge of /202patch.

**Comment by ericl-m3d** [comment]
Unloading options applied to the LCD section "Loading/Unloading Filament".
