### ISSUE TITLE
Remove automated motion from SD

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#48]
Due to hazards of unexpected movement, remove any automated motion at start up

**Comment by slipstreamliner** [comment]
As noted in (81c2659) -- what are your thoughts on moving all motor test calls to qc.g in a block of their own @ericl-m3d ?  This would remove the need to call any macros directly from config.g.  For now, they've been commented out.

**Comment by ericl-m3d** [comment]
Okay. Let's do that.

**Comment by ericl-m3d** [comment]
The movement macros in the qc.g do not need to be commented out. 

The M98 Pqc.g in the config.g file is commented out.

Needs fixing.

**Comment by ericl-m3d** [comment]
The same issue is occurring with the Bowdens. Needs fixing.
