### ISSUE TITLE
Start up QC issue

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#49]
Have the menu load first, then start the QC macros.

**Comment by slipstreamliner** [comment]
I am unsure if it's possible to force this in Firmware 2.02RC2 -- I believe a refresh option is available in RC5.  Let me do some additional research and get back to you here.

**Comment by ericl-m3d** [comment]
You're right. This may not be possible with the current firmware version. The 2.02RC4, as I recall, solved this issue.

So, this is pending RC4 compatibility (#4 )

**Comment by slipstreamliner** [comment]
Exactly. I think we should do the following for the next release:

First, after resolving the bugs here that can be resolved release version 1.32(internal 1.3, 2.02RC2) as things are now.  Then, post-upgrade, begin working on the 1.35(internal 1.3, 2.02RC5)as a separate release.  With that in mind, these issues could be rolled into a new milestone, project, or label.

**Comment by ericl-m3d** [comment]
Okay.

Please finish the issues #19 and #17 . Then move exclusively to working on RC5 (or RC4, whichever you think is the easiest to work with) compatibility.

All other issues are minor enough to disregard them for awhile, until we have the "upgrade compatibility"

**Comment by slipstreamliner** [comment]
Will do, updates coming momentarily for those in fact.

**Comment by slipstreamliner** [comment]
As for version -- RC4 vs RC5 should only be improvements for us, so if we're making a jump we should jump to 5.

**Comment by slipstreamliner** [comment]
Some fixes Rolled into #60 -- This will be resolved by the current open issue for a new way to load the QC menu.
