### ISSUE TITLE
Start Up QC Motion

### ISSUE THREAD

**Issue by ericl-m3d** [PrintM3D/Crane#50]
The secondary motion after hitting the endstop needs to be quicker.

**Comment by slipstreamliner** [comment]
After taking a look, I agree -- value was drastically lower than originally planned.   Following this next commit, the rate value for both X and Y axes will be 6000 and is reduced to 2/3 of that after hitting endstop(4000).  For the Z axis, the value 1200 is also 2/3 of its original rate, bringing it up to 800.
