### ISSUE TITLE
Tune/Prepare Main Menu Item Visibility Bug

### ISSUE THREAD

**Issue by slipstreamliner** [PrintM3D/Crane#76]
Typically this bug can be seen because the Main Menu area for the "Prepare" and "Tune" overlap and may appear as "Tuneare".

This is a basic overlap issue but can lead to a state in which the menu system is not responsive.   This is a primarily a notice and reminder to resolve this issue.   The 2.02 Full Release Milestone will include this fix.

**Comment by ericl-m3d** [comment]
Overlap bug has been addressed through layout formatting. Refer to the commits below:
2ba523a
9405f87
b7ceadd
