### ISSUE TITLE
Appropriate Steps/MM Value for Bowden, Dual, and Quad

### ISSUE THREAD

**Issue by slipstreamliner** [PrintM3D/Crane#77]
Would it be possible to get a consensus on the appropriate steps/mm value to utilize for all Crane printers?  I will be including this in the 2.02 update.  (I am having issues accessing discord at the moment.) Could I get a confirmation from @swblum or @ericl-m3d on this one?

**Comment by ericl-m3d** [comment]
Andrey already did that. 

807a33e

**Comment by slipstreamliner** [comment]
Thankyou Sir.
