### ISSUE TITLE
(Enhancement) Unload/Load Filament during pause

### ISSUE THREAD

**Issue by Tylerun** [PrintM3D/Crane#79]
Have had an issue where my filament spool ran out near completion of a print. I paused the print and attempted to unload and load a new one but the commands are not accesible. Any way to make them accesible? I know it can be donr via interface online but my computer is decently far away from my printer so i can not use that method.

**Comment by slipstreamliner** [comment]
Yes, we can move filament load/unload functionality to the paused state.  Will implement with 2.02.

**Comment by ericl-m3d** [comment]
Access to the unloading/loading section (during a paused print) has been implemented by these commits.

2ba523a
9405f87
b7ceadd
